Dodal test_main.cpp, razclenil c++ program na več datotek, dodal catch2 library

diff --git a/.github/workflows/27119_test.yml b/.github/workflows/27119_test.yml
--- a/.github/workflows/27119_test.yml
+++ b/.github/workflows/27119_test.yml
@@ -6,3 +6,12 @@ on:
 
 
 jobs:
+  check_test_scripts:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if test scripts exist
+        run: |
+          if [ ! -f .tests/test_main.cpp ]; then
+            echo "Test script test_main.cpp not found." > error.txt
+            exit 1
+          fi
